{{- include "wynn-tracker-server.validate" . -}}
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wynn-tracker-server.configSecretName" . }}
  labels:
    {{- include "wynn-tracker-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- include "wynn-tracker-server.configJson" . | nindent 4 }}
{{- end }}
